hello: ENC[AES256_GCM,data:USUUnSHskrjWGvMnOPK3RkQnhFjARCW7bCoyz6tjCZ1qkVtdwiHSCkUdTN9jcw==,iv:5H6nUSbsXWH7jBgnie2V3HbNRX0E15BfwNZwuvq0DN0=,tag:6MQgnbj3cQo+2t9/Z8FbIw==,type:str]
example_key: ENC[AES256_GCM,data:9ES8rKvBdC6nmlhjZg==,iv:Yj5SI7tXq5/q/887+AUzF/fvwzQk1fdGyeexuEGX6ME=,tag:HUFi9IrUGbfqoL6uzkqq2w==,type:str]
#ENC[AES256_GCM,data:NMTQ0Xb1PDqJe3NWOjAXrw==,iv:QnVV7qfd00BHBNkD6m1CU9IqsH4up+/EfurngURKDJY=,tag:Pv6irE2Ex68f1HpiKvAZiA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:e0EmBBu/nMq/f/ysnSk=,iv:ZSHlllO6X5Y9n4wLT5uy37Vdq0IGkKiOa0KuveDHxXs=,tag:M95+QazQm21DkyhAzS6mYA==,type:str]
    - ENC[AES256_GCM,data:X3iTK9pZT4aK6GLHQPI=,iv:1eTy/5Mk3C2onsw43SBu5huai+Jih3Zrtokn9XLECiU=,tag:o08R3gya4mOVCA+O9YtM8A==,type:str]
example_number: ENC[AES256_GCM,data:JNK9Hh6wkhI6cA==,iv:wQ0g6z1NFh+JzxgKv60VjIC/08BFTWPHGV73VyaonTE=,tag:pYtUFRobHGz+19WRmvojkg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:bgdwCw==,iv:8yjQ1d1kNxZOMKth6/jz0Y0xlpjgE0Ub3EAhY6nLesg=,tag:i2dLSr2cGxig6+trOrTurg==,type:bool]
    - ENC[AES256_GCM,data:4b4hQdA=,iv:T2R/n+vXD0AOnT4vrdOWKcWa3AHBe6c0FbdiDMew4hQ=,tag:87HTSGrNrDHsvilyQu/7xQ==,type:bool]
opencode_server:
    username: ENC[AES256_GCM,data:w0ZWfkU=,iv:mNBOXYzjw3oPgBj7LanzuSmnXQnZRCLqwSHC4JCSWnU=,tag:6H85zix1RV7B8EVOEeJyKw==,type:str]
    password: ENC[AES256_GCM,data:2Gnd10sugai5GiCxF3V70DhbSFovoyZRlhxKVa77kdkN/hNm3WHAaR8g,iv:TDiP16ypMtkBcWfhkJ6oDfvNwA153mXkFxxnMdDmxLg=,tag:UwjLEFHwUFKqP4xWd7+4nQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRem1PZm5ycm1KbWJRTHk2
            d1plRGY3U0VQNWlPSHBwNTN0S2lYc1JmWFNvCmRYQll5UjVNWEtrM3ZwdEplQWor
            SXUvb0llaTUzbzBVUlpwcHlvWkUrOUkKLS0tICsySzFkYzFQVnlnc2czdUJIS3l4
            cEU3RjBiMUE5R0ZtSi9kSzhrb1RCWk0Kz7q0WnDs5He4jR3HYHiqj5uggjIMzvVt
            /1tjrOcxfArlpMKow7+M2UyxGEpPFgYCcVvMtsF9w8/2Mag/vP6rJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r0f0ec2546aa5s5pdt4xsehtac9xmrr5cwvguhn3nrc2dytytytsk37nks
    lastmodified: "2026-07-08T13:28:25Z"
    mac: ENC[AES256_GCM,data:qXZr28A6tCtvGnSMTr7G+zUmkuc5ILCR2MslkUrcN7VczyMKfQswvPjCxPLKe8b0cPorNKe2HHze1zqRh8EvjDltp6fs/SGqg8Vgr/0MnYEDCM0AtMSHlTIVJEmA2FCalVQKCztNPIMV+0IByayQMOqOjb3AsZMuaMrQDZXFnOg=,iv:M2qDm+NoALUrDp8zFgr5zNj5LVbCqcm5gr0VFEbrPJE=,tag:DU7waUZWOr1xfS9fnwWjIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
