config_version = 12

[bar]
order = [ "Linca", "task" ]

    [bar.Linca]
    background_opacity = 0.0
    capsule = true
    capsule_padding = 5.0
    center = [ "active_window", "media" ]
    end = [ "tray", "group:g3", "network", "group:g2", "battery", "clock" ]
    font_family = "Noto Sans"
    margin_edge = 0
    margin_ends = 0
    scale = 0.85000000521540642
    shadow = false
    start = [ "workspaces", "group:g1", "weather" ]
    thickness = 25
    widget_spacing = 3

        [[bar.Linca.capsule_group]]
        fill = "surface_variant"
        id = "g1"
        members = [ "cpu", "sysmon" ]
        opacity = 1.0
        padding = 4.0

        [[bar.Linca.capsule_group]]
        fill = "surface_variant"
        id = "g2"
        members = [ "bluetooth", "volume", "brightness", "notifications" ]
        opacity = 1.0
        padding = 4.0

        [[bar.Linca.capsule_group]]
        fill = "surface_variant"
        id = "g3"
        members = [ "wallhaven", "clipboard" ]
        opacity = 1.0
        padding = 4.0

    [bar.task]
    center = [ "control-center", "launcher", "taskbar" ]
    concave_edge_corners = true
    enabled = true
    end = [ "tray_2", "group:g1", "group:g2" ]
    font_family = "Noto Sans"
    margin_edge = 0
    margin_ends = 0
    position = "bottom"
    radius = 0
    radius_bottom_right = 80
    start = [ "wallpaper", "weather", "audio_visualizer", "media" ]
    thickness = 45
    widget_spacing = 9

        [[bar.task.capsule_group]]
        fill = "surface_variant"
        id = "g1"
        members = [ "network_2", "volume_2", "battery" ]
        opacity = 1.0
        padding = 6.0

        [[bar.task.capsule_group]]
        fill = "surface_variant"
        id = "g2"
        members = [ "spacer_2", "clock_2", "notifications" ]
        opacity = 1.0
        padding = 6.0

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006"
]

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 240.0
    box_width = 240.0
    cx = 169.5
    cy = 185.5
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        show_forecast = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 96.0
    box_width = 240.0
    cx = 169.5
    cy = 389.5
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 128.0
    box_width = 480.0
    cx = 549.5
    cy = 129.5
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 128.0
    box_width = 224.0
    cx = 421.5
    cy = 277.5
    output = "eDP-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 128.0
    box_width = 224.0
    cx = 677.5
    cy = 277.5
    output = "eDP-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        stat = "ram_pct"
        stat2 = "swap_pct"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 96.0
    box_width = 704.0
    cx = 1317.5
    cy = 133.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        format = "{:%B %d}, {:%A}, {:%H:%M:%S}"

[dock]
auto_hide = true
reserve_space = false
show_dots = true

[hooks]
theme_mode_changed = "dconf write /org/gnome/desktop/interface/color-scheme \"\\\"prefer-$NOCTALIA_THEME_MODE\\\"\""

[idle]
behavior_order = [ "idle-behavior", "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.idle-behavior]
    action = "lock"
    enabled = false
    timeout = 30.0

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Nanjing,China"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-5",
    "lockscreen-login-box@winit",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 70.0
    box_width = 400.0
    cx = 1024.0
    cy = 1033.0
    output = "DP-5"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 854.0
    cy = 948.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 621.0
    cy = 1428.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 80.0
    box_width = 256.0
    cx = 325.5
    cy = 133.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 128.0
    box_width = 368.0
    cx = 269.5
    cy = 261.5
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 96.0
    box_width = 368.0
    cx = 269.5
    cy = 389.5
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        bands = 32
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 112.0
    box_width = 240.0
    cx = 1533.5
    cy = 149.5
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 96.0
    box_width = 96.0
    cx = 133.5
    cy = 133.5
    output = "eDP-1"
    rotation = 0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        image_path = "/home/linca/nixos/home/linca/assets/avatar.png"
        opacity = 1.0

[notification]
layer = "overlay"
scale = 0.90000000596046448
show_actions = false

[plugin_settings."noctalia/wallhaven"]
api_key = "JfwpcGqM5hkMYp1e5TrStGittuZXNS9a"

[plugins]
enabled = [ "noctalia/wallhaven" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
avatar_path = "/home/linca/.face"
lang = "zh-Hans"
settings_show_advanced = true

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    transparency_mode = "soft"

    [shell.screenshot]
    directory = "~/Pictures/Screenshots"

[theme]
builtin = "Ayu"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "niri" ]
    community_ids = [ "zed" ]

[wallpaper]
directory = "/home/linca/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/linca/Pictures/Wallpapers/1.png"

    [wallpaper.last]
    path = "/home/linca/Pictures/Wallpapers/1.png"

    [wallpaper.monitors.DP-5]
    path = "/home/linca/Pictures/Wallpapers/Arus_花火r18_117146413_p0.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/linca/Pictures/Wallpapers/1.png"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/linca/Pictures/Wallpapers/1.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[widget.audio_visualizer]
bands = 20
color_2 = "secondary"

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

    [widget.brightness.actions]
    scroll_down = "brightness-down 1%"
    scroll_up = "brightness-up 1%"

[widget.cat]
scale = 1.2
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clock]
format = "{:%H:%M:%S}"

[widget.clock_2]
format = "{:%H:%M:%S}\\n{:%Y/%m/%d}"
type = "clock"

[widget.control-center]
custom_image = "/home/linca/HyDE/Source/assets/nixos.png"
scale = 1.6000000000000001

[widget.launcher]
scale = 1.6000000000000001

[widget.media]
hide_when_no_media = true
max_length = 160
title_scroll = "always"

[widget.my-launcher]
glyph = "rocket"
type = "custom_button"

[widget.network_2]
show_label = false
type = "network"

[widget.spacer_2]
length = 5
type = "spacer"

[widget.sysmon]
stat = "ram_pct"

[widget.taskbar]
group_by_workspace = true
group_single_icon_per_app = true
hide_empty_workspaces = true
scale = 1.6000000000000001

[widget.tray]
capsule = true
capsule_padding = 8.0

[widget.tray_2]
detached_panel = true
drawer = true
drawer_columns = 5
pinned = [ "Telegram Desktop", "v2rayN", "Fcitx", "chrome_status_icon_1", "steam" ]
type = "tray"

[widget.volume]
show_label = false

[widget.volume_2]
show_label = false
type = "volume"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
active_pill_size = 1.75
label_source = "name"
labels_only_when_occupied = true